services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: eshop
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: eshop
      MYSQL_PASSWORD: eshoppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eshopnet

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - eshopnet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - eshopnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: eshop
      PMA_PASSWORD: eshoppassword
    ports:
      - "8082:80"
    depends_on:
      - mysql
    networks:
      - eshopnet

volumes:
  mysql_data:

networks:
  eshopnet:
